### ISSUE TITLE
#US19 Como cliente deseo comprar un producto para satisfacer mis necesidades

### ISSUE THREAD

**Issue by CaronlineArg** [PulpoI/proyecto-integrador-ISPC#140]

**Comment by CaronlineArg** [comment]
Al comprar un/os producto/s debe visualizar sus características, precio, cantidad, total y subtotal, además de elegir método de pago(mercado pago o tarjeta).

**Comment by PulpoI** [comment]
No es necesario el carrito ya que se adquiere un solo servicio (plan)
Resumen del sitio:

- Un Admin se encarga de crear Planes con diferentes beneficios, el principal beneficio es la asistencia a determinada cantidad de Clases. Estas clases tambien las proporciona el Admin.

- Un Cliente se registra/loguea para poder adquirir un Plan el cual le da varios beneficios. Entre ellos asistir al gimnasio durante un tiempo determinado y asistir a una determinada cantidad de clases (dependiendo del plan).

Desarrollar la página "Planes" de forma dinámica para que cada plan al ser elegido lleve al cliente a un checkout que contenga la info del plan elegido.

**Comment by CaronlineArg** [comment]
faltaria poder conectar a una base de datos de checkout para almacenar la compra en el usuario

**Comment by CaronlineArg** [comment]
ya agregue en el boton de compra que rediriga al login si no esta logueado pero creo que hay que arreglarlo

**Comment by CaronlineArg** [comment]
Falta ticket de compra con mercado pago. Off tópic: habría que hacer un ticket sobre testeo, debugeo y otro sobre  chekear que sea responsive la página después de la implementación de la feature e-commerce.
