### ISSUE TITLE
#TK71 Modificar documentacion IEE-830 - Actualizar

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#158]

**Comment by PulpoI** [comment]
Revisar el documento IEE-830 y modificar para que coincida con lo que es nuestro sitio.
Resumen:
- Un Admin se encarga de crear Planes con diferentes beneficios, el principal beneficio es la asistencia a determinada cantidad de Clases. Estas clases tambien las proporciona el Admin.
- Un Cliente se registra/loguea para poder adquirir un Plan el cual le da varios beneficios. Entre ellos asistir al gimnasio durante un tiempo determinado y asistir a una determinada cantidad de clases (dependiendo del plan).

**Comment by PulpoI** [comment]
Enlace a carpeta con los documentos: 
[https://drive.google.com/drive/u/2/folders/1JrKXOAgImliu8LByMGikNy2PULYRkGhc](url)

Editarlo en linea en Word. 
Cuando este listo se guarda en PDF para subir al repositorio

**Comment by Sole1988** [comment]
Hecho
