### ISSUE TITLE
#US24 Como administrador deseo ver avisos al agregar/eliminar Clases y Planes

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#189]
- Deberán informar al usuario mediante mensajes personalizados (Validaciones)
- Deberán respetar los colores semánticos que propone Bootstrap, https://getbootstrap.com/docs/5.0/utilities/borders/ Por ej. 
<span class="border border-success"></span>
<span class="border border-danger"></span>

**Comment by CaronlineArg** [comment]
No entendí la issue, necesito que sea más especifica

**Comment by CaronlineArg** [comment]
resuelta
