### ISSUE TITLE
#TK08 Crear página de Perfil 

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#19]

**Comment by julieta-10-stor** [comment]
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>pagina de perfil</title>
    </head>

    <body>
        
    </body>
</html>

    <header>
        <h1>Gym App</h1>
        <h2>home</h2>
        <h3>nosostros</h3>
        <h4>turnos</h4>
        <h5>perfil</h5>
        <h6>contacto</h6>
        <h7>iniciar sesion</h7>
        <h8>registrarse</h8>
    </header>

     <footer> 
     <h1>domicilio</h1>
     <h2>ubicacion</h2>
     <h3>correo electronico</h3>
     <h4>telefono</h4>
     </footer>

     <nav>
        <nl>
            <li><a href="index.html">inicio</a></li>
            <li><a href="contact.html">contactos</a</li>
            <li><a href="information.html">informacion</a></li> 
            <li><a href="photos.html">fotos</a></li>   
        </nl>
     </nav>

     <section>
        <h1>seccion de mi pagina</h1>
        <p>contenidos</p>
     </section>

     <aside>
     <La gimnasia es buena para la mayoría de las personas, ya que la necesitan en un cierto límite y cuidado. Son ciertas para fundamentalmente el desarrollando de nuevas características mentales y físicas. fueron desarrolladas para tener objetivos que uno quiere desarrollar garantizando los beneficios de las actividades físicas organizadas.>
     </aside>
     
     <articule> 
        <h1> Mi articulo</h1>
        <p>Algunas maneras divertidas para que los adultos mayores se mantengan físicamente activos 
            https://www.nia.nih.gov/espanol/algunas-maneras-divertidas-adultos-mayores-se-mantengan-fisicamente-activos
        </p>
     </articule>

     <!DOCTYPE html>
     <html> 
        <head> 
            <title>Gym App</title>
        </head>
        <body>
            <p style=""color black; font-perfil;gimnasia">la gimnacia es un buen movimineto para unaestra salud</p>
        </body>
     </html>

     <!doctype html>
     <html> 
        <head> 
            <title>Gym App</title>
            <style type="text/css">
                p[ 
                 color:black;
                    font-perfil:gimnasia  
                ]
            </style>
         </head>
         <body> 
            <p>la gimnacia es un buen movimineto para unaestra salud</p>
            </body>
     </html>

     p[color:bñack;font-perfil:gimnasia;]
     <!doctype html>
    <html>
    <head>
        <titule>Gym App</titule>
        <link rel="stylesheet"type="text/css" href="/www./GymApp.com" media="screen" />       
     </head>
     <body>
        <p>La gimnacia es un buen movimineto para unaestra salud</p>
        </body>
    </html>
