### ISSUE TITLE
#TK09 4.3 Modelado de Base de Datos 4.3.1. Modelo Entidad Relación

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#21]
Modelado de DB. DER, Modelo Relacional.

**Comment by CelesRivarola** [comment]
![Image](https://user-images.githubusercontent.com/87398816/196049217-ddaedeaa-2cc1-4aac-84c6-fafc1fd734d1.png)
![Image](https://user-images.githubusercontent.com/87398816/196049218-b14dca86-06d8-46e1-8cf6-18134976521a.png)

**Comment by CelesRivarola** [comment]
Modelo relacional y Modelado
