### ISSUE TITLE
#TK10 4. Análisis 4.1. Definicion Diagrama de Clase

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#22]

**Comment by juliboiola** [comment]
Inserto archivo con el punto asignado


[Análisis 4.1. Definicion Diagrama de Clase #22.pdf](https://github.com/PulpoI/proyecto-integrador-ISPC/files/9796680/Analisis.4.1.Definicion.Diagrama.de.Clase.22.pdf)
