### ISSUE TITLE
#TK16 4. Análisis 4.2.4. Diagrama de Caso de Uso específico Administrar cuentas

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#29]

**Comment by rosrob** [comment]
Se insertó diagrama.


![Image](https://user-images.githubusercontent.com/105127792/196254269-4cf43ca1-6a51-4b95-953c-819994e855cb.png)

**Comment by rosrob** [comment]
Diagrama de  caso de usos - Administrar cuentas
