### ISSUE TITLE
#TK17 4. Análisis 4.2.5. Diagrama de Caso de Uso específico Administrar Sesiones

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#30]

**Comment by Sole1988** [comment]
Se inserto diagrama en documento IEEE-830

**Comment by Sole1988** [comment]
![2022-10-14](https://user-images.githubusercontent.com/94577357/196037519-aaa4e4ca-3529-448a-bfe7-fa7485eb5152.png)
