### ISSUE TITLE
#TK25 (Wordpress)  Tecnologías - Python

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#54]
7) En la opción de Tecnologías debe crear una subopción por cada tecnología que
conozca como grupo; por ejemplo si conoce “Python, MySql y Wordpress” deberá
crear una subopción para cada una.
● Cada subopción debe constar de una página en donde explique en qué
consiste y para qué sirve esa tecnología.

**Comment by juliboiola** [comment]
Realizada la sección de Python -tecnologías- del portfolio grupal.
