### ISSUE TITLE
#TK26 (Wordpress) Tecnologías - MySql

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#55]
7) En la opción de Tecnologías debe crear una subopción por cada tecnología que
conozca como grupo; por ejemplo si conoce “Python, MySql y Wordpress” deberá
crear una subopción para cada una.
● Cada subopción debe constar de una página en donde explique en qué
consiste y para qué sirve esa tecnología.

**Comment by MajoMalbran** [comment]
Realizada la sección de MySQL en la subopcion "Tecnologías" del portafolio grupal.
