### ISSUE TITLE
#TK29 Construcción de las clases en Python

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#58]
En relación a la Abstracción, deben:
En primer lugar crear el Diagrama de Clases (modelo de objetos). Pueden usar como herramienta también https://app.diagrams.net/
En segundo lugar, la construcción de las clases utilizando el lenguaje de programación en Python. Hay videos explicativos en el apartado de Backend.

**Comment by Sole1988** [comment]
Se realizó en base al diagrama de clases del documento IEEE-830
