### ISSUE TITLE
#TK32 (Wordpress) Tecnologías - Wordpress

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#63]
7) En la opción de Tecnologías debe crear una subopción por cada tecnología que
conozca como grupo; por ejemplo si conoce “Python, MySql y Wordpress” deberá
crear una subopción para cada una.
● Cada subopción debe constar de una página en donde explique en qué
consiste y para qué sirve esa tecnología.

**Comment by IvanMR94** [comment]
Realizada la sección de WordpPress en la subocion "Tecnologías" del portafolio grupal.
