### ISSUE TITLE
#TK37 (Wordpress) Integrantes

### ISSUE THREAD

**Issue by PulpoI** [PulpoI/proyecto-integrador-ISPC#68]
6) La opción Integrantes desplegará un submenú con el nombre y apellido de cada
integrante del grupo.
● Al hacer clic en el nombre respectivo deberá de mostrar su Currículum Vitae
(CV).
● Cada CV debe estar publicado por el propietario del mismo

**Comment by CaronlineArg** [comment]
Ya realicé mi sección de integrante

**Comment by IvanMR94** [comment]
Realizada mi sección de integrante.

**Comment by MajoMalbran** [comment]
He realizado mi sección de integrante

**Comment by PulpoI** [comment]
Realizado

**Comment by juliboiola** [comment]
Realizado

**Comment by CelesRivarola** [comment]
Realizado.
